// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NetworkMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace sRPC {

  /// <summary>Holder for reflection information generated from NetworkMessage.proto</summary>
  public static partial class NetworkMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for NetworkMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetworkMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChROZXR3b3JrTWVzc2FnZS5wcm90bxIEc3JwYxoZZ29vZ2xlL3Byb3RvYnVm",
            "L2FueS5wcm90byKFAQoOTmV0d29ya1JlcXVlc3QSFAoMYXBpX2Z1bmN0aW9u",
            "GAEgASgJEiUKB3JlcXVlc3QYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55",
            "Eg0KBXRva2VuGAMgASgDEhYKDmNhbmNlbFJlcXVlc3RzGAQgAygDEg8KB3Jl",
            "dmVyc2UYBSABKAgiWQoPTmV0d29ya1Jlc3BvbnNlEiYKCHJlc3BvbnNlGAIg",
            "ASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueRINCgV0b2tlbhgDIAEoAxIPCgdy",
            "ZXZlcnNlGAUgASgIQgeqAgRzUlBDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::sRPC.NetworkRequest), global::sRPC.NetworkRequest.Parser, new[]{ "ApiFunction", "Request", "Token", "CancelRequests", "Reverse" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::sRPC.NetworkResponse), global::sRPC.NetworkResponse.Parser, new[]{ "Response", "Token", "Reverse" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// the base request information that is used be the internal Api
  /// </summary>
  public sealed partial class NetworkRequest : pb::IMessage<NetworkRequest> {
    private static readonly pb::MessageParser<NetworkRequest> _parser = new pb::MessageParser<NetworkRequest>(() => new NetworkRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetworkRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::sRPC.NetworkMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkRequest(NetworkRequest other) : this() {
      apiFunction_ = other.apiFunction_;
      request_ = other.request_ != null ? other.request_.Clone() : null;
      token_ = other.token_;
      cancelRequests_ = other.cancelRequests_.Clone();
      reverse_ = other.reverse_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkRequest Clone() {
      return new NetworkRequest(this);
    }

    /// <summary>Field number for the "api_function" field.</summary>
    public const int ApiFunctionFieldNumber = 1;
    private string apiFunction_ = "";
    /// <summary>
    /// the name of the api function to request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ApiFunction {
      get { return apiFunction_; }
      set {
        apiFunction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any request_;
    /// <summary>
    /// the request object with the data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Request {
      get { return request_; }
      set {
        request_ = value;
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 3;
    private long token_;
    /// <summary>
    /// the token to identify the response with the request
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "cancelRequests" field.</summary>
    public const int CancelRequestsFieldNumber = 4;
    private static readonly pb::FieldCodec<long> _repeated_cancelRequests_codec
        = pb::FieldCodec.ForInt64(34);
    private readonly pbc::RepeatedField<long> cancelRequests_ = new pbc::RepeatedField<long>();
    /// <summary>
    /// a list of token ids which has the request canceld.
    /// The server should now stop the computation of the response.
    /// There is no response message needed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> CancelRequests {
      get { return cancelRequests_; }
    }

    /// <summary>Field number for the "reverse" field.</summary>
    public const int ReverseFieldNumber = 5;
    private bool reverse_;
    /// <summary>
    /// determine if the message is for the reverse direction. Only used
    /// for interfaces that supports API calls in both directions.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Reverse {
      get { return reverse_; }
      set {
        reverse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetworkRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetworkRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ApiFunction != other.ApiFunction) return false;
      if (!object.Equals(Request, other.Request)) return false;
      if (Token != other.Token) return false;
      if(!cancelRequests_.Equals(other.cancelRequests_)) return false;
      if (Reverse != other.Reverse) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ApiFunction.Length != 0) hash ^= ApiFunction.GetHashCode();
      if (request_ != null) hash ^= Request.GetHashCode();
      if (Token != 0L) hash ^= Token.GetHashCode();
      hash ^= cancelRequests_.GetHashCode();
      if (Reverse != false) hash ^= Reverse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ApiFunction.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApiFunction);
      }
      if (request_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Request);
      }
      if (Token != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Token);
      }
      cancelRequests_.WriteTo(output, _repeated_cancelRequests_codec);
      if (Reverse != false) {
        output.WriteRawTag(40);
        output.WriteBool(Reverse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ApiFunction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiFunction);
      }
      if (request_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Request);
      }
      if (Token != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Token);
      }
      size += cancelRequests_.CalculateSize(_repeated_cancelRequests_codec);
      if (Reverse != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetworkRequest other) {
      if (other == null) {
        return;
      }
      if (other.ApiFunction.Length != 0) {
        ApiFunction = other.ApiFunction;
      }
      if (other.request_ != null) {
        if (request_ == null) {
          Request = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Request.MergeFrom(other.Request);
      }
      if (other.Token != 0L) {
        Token = other.Token;
      }
      cancelRequests_.Add(other.cancelRequests_);
      if (other.Reverse != false) {
        Reverse = other.Reverse;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ApiFunction = input.ReadString();
            break;
          }
          case 18: {
            if (request_ == null) {
              Request = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Request);
            break;
          }
          case 24: {
            Token = input.ReadInt64();
            break;
          }
          case 34:
          case 32: {
            cancelRequests_.AddEntriesFrom(input, _repeated_cancelRequests_codec);
            break;
          }
          case 40: {
            Reverse = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// the base response information that is used be the internal Api
  /// </summary>
  public sealed partial class NetworkResponse : pb::IMessage<NetworkResponse> {
    private static readonly pb::MessageParser<NetworkResponse> _parser = new pb::MessageParser<NetworkResponse>(() => new NetworkResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetworkResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::sRPC.NetworkMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkResponse(NetworkResponse other) : this() {
      response_ = other.response_ != null ? other.response_.Clone() : null;
      token_ = other.token_;
      reverse_ = other.reverse_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetworkResponse Clone() {
      return new NetworkResponse(this);
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any response_;
    /// <summary>
    /// the response object with the data.
    /// if the response is empty that means the server has cancelled it by itself
    /// (this behaviour is not recommended - include the error information in your response!).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Any Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 3;
    private long token_;
    /// <summary>
    /// the token to identify this response
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "reverse" field.</summary>
    public const int ReverseFieldNumber = 5;
    private bool reverse_;
    /// <summary>
    /// determine if the message is for the reverse direction. Only used
    /// for interfaces that supports API calls in both directions.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Reverse {
      get { return reverse_; }
      set {
        reverse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetworkResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetworkResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Response, other.Response)) return false;
      if (Token != other.Token) return false;
      if (Reverse != other.Reverse) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (response_ != null) hash ^= Response.GetHashCode();
      if (Token != 0L) hash ^= Token.GetHashCode();
      if (Reverse != false) hash ^= Reverse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (Token != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Token);
      }
      if (Reverse != false) {
        output.WriteRawTag(40);
        output.WriteBool(Reverse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (Token != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Token);
      }
      if (Reverse != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetworkResponse other) {
      if (other == null) {
        return;
      }
      if (other.response_ != null) {
        if (response_ == null) {
          Response = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Response.MergeFrom(other.Response);
      }
      if (other.Token != 0L) {
        Token = other.Token;
      }
      if (other.Reverse != false) {
        Reverse = other.Reverse;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (response_ == null) {
              Response = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Response);
            break;
          }
          case 24: {
            Token = input.ReadInt64();
            break;
          }
          case 40: {
            Reverse = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
