// <auto-generated>
//     Generated by the sRPC compiler.  DO NOT EDIT!
//     source: simple_service.proto
// </auto-generated>
#pragma warning disable CS0067, CS0076, CS0612, CS1591, CS1998, CS3021
#region Designer generated code

using gp = global::Google.Protobuf;
using gpw = global::Google.Protobuf.WellKnownTypes;
using s = global::System;
using scg = global::System.Collections.Generic;
using global::System.Linq;
using srpc = global::sRPC;
using st = global::System.Threading;
using stt = global::System.Threading.Tasks;

namespace ExampleProject
{
    /// <summary>
    /// The base class for the client implementation of the SimpleService api
    /// </summary>
    public class SimpleServiceClient : srpc::IApiClientDefinition2
    {
        event s::Func<srpc::NetworkRequest, stt::Task<srpc::NetworkResponse>> srpc::IApiClientDefinition.PerformMessage
        {
            add => PerformMessagePrivate += value;
            remove => PerformMessagePrivate -= value;
        }

        event s::Func<srpc::NetworkRequest, st::CancellationToken, stt::Task<srpc::NetworkResponse>> srpc::IApiClientDefinition2.PerformMessage2
        {
            add => PerformMessage2Private += value;
            remove => PerformMessage2Private -= value;
        }

        private event s::Func<srpc::NetworkRequest, stt::Task<srpc::NetworkResponse>> PerformMessagePrivate;

        private event s::Func<srpc::NetworkRequest, st::CancellationToken, stt::Task<srpc::NetworkResponse>> PerformMessage2Private;

        public virtual stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(ExampleProject.RandonNumberRequest message)
        {
            _ = message ?? throw new s::ArgumentNullException(nameof(message));
            return GetRandomNumber(message, st::CancellationToken.None);
        }

        public virtual async stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(ExampleProject.RandonNumberRequest message, st::CancellationToken cancellationToken)
        {
            _ = message ?? throw new s::ArgumentNullException(nameof(message));
            var networkMessage = new srpc::NetworkRequest()
            {
                ApiFunction = "GetRandomNumber",
                Request = gpw::Any.Pack(message),
            };
            var response = PerformMessage2Private != null
                ? await PerformMessage2Private.Invoke(networkMessage, cancellationToken)
                : await PerformMessagePrivate?.Invoke(networkMessage);
            return response.Response?.Unpack<ExampleProject.RandomNumberResponse>();
        }

        public virtual async stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(ExampleProject.RandonNumberRequest message, s::TimeSpan timeout)
        {
            _ = message ?? throw new s::ArgumentNullException(nameof(message));
            if (timeout.Ticks < 0)
                throw new s::ArgumentOutOfRangeException(nameof(timeout));
            using var cancellationToken = new st::CancellationTokenSource(timeout);
            return await GetRandomNumber(message, cancellationToken.Token);
        }

		public virtual stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(
			int @count = 0,
			int @minValue = 0,
			int @maxValue = 0)
        {
            var request = new ExampleProject.RandonNumberRequest
            {
				Count = @count,
				MinValue = @minValue,
				MaxValue = @maxValue,
            };
            return GetRandomNumber(request);
        }

		public virtual stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(
			st::CancellationToken cancellationToken,
			int @count = 0,
			int @minValue = 0,
			int @maxValue = 0)
        {
            var request = new ExampleProject.RandonNumberRequest
            {
				Count = @count,
				MinValue = @minValue,
				MaxValue = @maxValue,
            };
            return GetRandomNumber(request, cancellationToken);
        }

		public virtual stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(
			s::TimeSpan timeout,
			int @count = 0,
			int @minValue = 0,
			int @maxValue = 0)
        {
            var request = new ExampleProject.RandonNumberRequest
            {
				Count = @count,
				MinValue = @minValue,
				MaxValue = @maxValue,
            };
            return GetRandomNumber(request, timeout);
        }
    }

    /// <summary>
    /// The base class for the server implementation of the SimpleService api
    /// </summary>
    public abstract class SimpleServiceServerBase : srpc::IApiServerDefinition2
    {
        stt::Task<srpc::NetworkResponse> srpc::IApiServerDefinition.HandleMessage(srpc::NetworkRequest request)
            => ((srpc::IApiServerDefinition2)this).HandleMessage2(request, st::CancellationToken.None);

        async stt::Task<srpc::NetworkResponse> srpc::IApiServerDefinition2.HandleMessage2(srpc::NetworkRequest request, st::CancellationToken cancellationToken)
        {
            _ = request ?? throw new s::ArgumentNullException(nameof(request));
            switch (request.ApiFunction)
            {
                case "GetRandomNumber":
                    return new srpc::NetworkResponse()
                    {
                        Response = gpw::Any.Pack(await GetRandomNumber(request.Request?.Unpack<ExampleProject.RandonNumberRequest>(), cancellationToken)),
                        Token = request.Token,
                    };
                default: throw new s::NotSupportedException($"{request.ApiFunction} is not defined");
            }
        }

        public abstract stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(ExampleProject.RandonNumberRequest request);

        public virtual stt::Task<ExampleProject.RandomNumberResponse> GetRandomNumber(ExampleProject.RandonNumberRequest request, st::CancellationToken cancellationToken)
            => GetRandomNumber(request);
    }
}

#endregion Designer generated code
