// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/build_test_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace sRPC.Test.Proto {

  /// <summary>Holder for reflection information generated from Proto/build_test_service.proto</summary>
  public static partial class BuildTestServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/build_test_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuildTestServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5Qcm90by9idWlsZF90ZXN0X3NlcnZpY2UucHJvdG8SCXNycGMudGVzdBob",
            "Z29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGh9nb29nbGUvcHJvdG9idWYv",
            "dGltZXN0YW1wLnByb3RvItIICgtNdWx0aUZpZWxkcxIRCglib29sX2ZsYWcY",
            "ASABKAgSEwoLYnl0ZXNfdmFsdWUYAiABKAwSFAoMZG91YmxlX3ZhbHVlGAMg",
            "ASgBEikKCmVudW1fdmFsdWUYBCABKA4yFS5zcnBjLnRlc3QuRW51bU9iamVj",
            "dBIVCg1maXhlZDMyX3ZhbHVlGAUgASgHEhUKDWZpeGVkNjRfdmFsdWUYBiAB",
            "KAYSEwoLZmxvYXRfdmFsdWUYByABKAISEwoLaW50MzJfdmFsdWUYCCABKAUS",
            "EwoLaW50NjRfdmFsdWUYCSABKAMSMQoNbWVzc2FnZV92YWx1ZRgKIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASFgoOc2ZpeGVkMzJfdmFsdWUY",
            "CyABKA8SFgoOc2ZpeGVkNjRfdmFsdWUYDCABKBASFAoMc2ludDMyX3ZhbHVl",
            "GA0gASgREhQKDHNpbnQ2NF92YWx1ZRgOIAEoEhIUCgxzdHJpbmdfdmFsdWUY",
            "DyABKAkSFAoMdWludDMyX3ZhbHVlGBAgASgNEhQKDHVpbnQ2NF92YWx1ZRgR",
            "IAEoBBIaChJyZXBlYXRlZF9ib29sX2ZsYWcYFSADKAgSHAoUcmVwZWF0ZWRf",
            "Ynl0ZXNfdmFsdWUYFiADKAwSHQoVcmVwZWF0ZWRfZG91YmxlX3ZhbHVlGBcg",
            "AygBEjIKE3JlcGVhdGVkX2VudW1fdmFsdWUYGCADKA4yFS5zcnBjLnRlc3Qu",
            "RW51bU9iamVjdBIeChZyZXBlYXRlZF9maXhlZDMyX3ZhbHVlGBkgAygHEh4K",
            "FnJlcGVhdGVkX2ZpeGVkNjRfdmFsdWUYGiADKAYSHAoUcmVwZWF0ZWRfZmxv",
            "YXRfdmFsdWUYGyADKAISHAoUcmVwZWF0ZWRfaW50MzJfdmFsdWUYHCADKAUS",
            "HAoUcmVwZWF0ZWRfaW50NjRfdmFsdWUYHSADKAMSOgoWcmVwZWF0ZWRfbWVz",
            "c2FnZV92YWx1ZRgeIAMoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAS",
            "HwoXcmVwZWF0ZWRfc2ZpeGVkMzJfdmFsdWUYHyADKA8SHwoXcmVwZWF0ZWRf",
            "c2ZpeGVkNjRfdmFsdWUYICADKBASHQoVcmVwZWF0ZWRfc2ludDMyX3ZhbHVl",
            "GCEgAygREh0KFXJlcGVhdGVkX3NpbnQ2NF92YWx1ZRgiIAMoEhIdChVyZXBl",
            "YXRlZF9zdHJpbmdfdmFsdWUYIyADKAkSHQoVcmVwZWF0ZWRfdWludDMyX3Zh",
            "bHVlGCQgAygNEh0KFXJlcGVhdGVkX3VpbnQ2NF92YWx1ZRglIAMoBBIvCgVt",
            "YXBfMRgoIAMoCzIgLnNycGMudGVzdC5NdWx0aUZpZWxkcy5NYXAxRW50cnka",
            "KwoJTWFwMUVudHJ5EgsKA2tleRgBIAEoBRINCgV2YWx1ZRgCIAEoCToCOAEi",
            "HgoJSWRlbnRpY2FsEhEKCWlkZW50aWNhbBgBIAEoDCoxCgpFbnVtT2JqZWN0",
            "EhEKDURFRkFVTFRfVkFMVUUQABIQCgxTRUNPTkRfVkFMVUUQATKUAQoQQnVp",
            "bGRUZXN0U2VydmljZRJBCg9UZXN0TXVsdGlGaWVsZHMSFi5zcnBjLnRlc3Qu",
            "TXVsdGlGaWVsZHMaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSPQoNVGVzdElk",
            "ZW50aWNhbBIULnNycGMudGVzdC5JZGVudGljYWwaFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHlCEqoCD3NSUEMuVGVzdC5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::sRPC.Test.Proto.EnumObject), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::sRPC.Test.Proto.MultiFields), global::sRPC.Test.Proto.MultiFields.Parser, new[]{ "BoolFlag", "BytesValue", "DoubleValue", "EnumValue", "Fixed32Value", "Fixed64Value", "FloatValue", "Int32Value", "Int64Value", "MessageValue", "Sfixed32Value", "Sfixed64Value", "Sint32Value", "Sint64Value", "StringValue", "Uint32Value", "Uint64Value", "RepeatedBoolFlag", "RepeatedBytesValue", "RepeatedDoubleValue", "RepeatedEnumValue", "RepeatedFixed32Value", "RepeatedFixed64Value", "RepeatedFloatValue", "RepeatedInt32Value", "RepeatedInt64Value", "RepeatedMessageValue", "RepeatedSfixed32Value", "RepeatedSfixed64Value", "RepeatedSint32Value", "RepeatedSint64Value", "RepeatedStringValue", "RepeatedUint32Value", "RepeatedUint64Value", "Map1" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::sRPC.Test.Proto.Identical), global::sRPC.Test.Proto.Identical.Parser, new[]{ "Identical_" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EnumObject {
    [pbr::OriginalName("DEFAULT_VALUE")] DefaultValue = 0,
    [pbr::OriginalName("SECOND_VALUE")] SecondValue = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  /// this message type contains a wide variety of field types
  /// </summary>
  public sealed partial class MultiFields : pb::IMessage<MultiFields> {
    private static readonly pb::MessageParser<MultiFields> _parser = new pb::MessageParser<MultiFields>(() => new MultiFields());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MultiFields> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::sRPC.Test.Proto.BuildTestServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiFields() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiFields(MultiFields other) : this() {
      boolFlag_ = other.boolFlag_;
      bytesValue_ = other.bytesValue_;
      doubleValue_ = other.doubleValue_;
      enumValue_ = other.enumValue_;
      fixed32Value_ = other.fixed32Value_;
      fixed64Value_ = other.fixed64Value_;
      floatValue_ = other.floatValue_;
      int32Value_ = other.int32Value_;
      int64Value_ = other.int64Value_;
      messageValue_ = other.messageValue_ != null ? other.messageValue_.Clone() : null;
      sfixed32Value_ = other.sfixed32Value_;
      sfixed64Value_ = other.sfixed64Value_;
      sint32Value_ = other.sint32Value_;
      sint64Value_ = other.sint64Value_;
      stringValue_ = other.stringValue_;
      uint32Value_ = other.uint32Value_;
      uint64Value_ = other.uint64Value_;
      repeatedBoolFlag_ = other.repeatedBoolFlag_.Clone();
      repeatedBytesValue_ = other.repeatedBytesValue_.Clone();
      repeatedDoubleValue_ = other.repeatedDoubleValue_.Clone();
      repeatedEnumValue_ = other.repeatedEnumValue_.Clone();
      repeatedFixed32Value_ = other.repeatedFixed32Value_.Clone();
      repeatedFixed64Value_ = other.repeatedFixed64Value_.Clone();
      repeatedFloatValue_ = other.repeatedFloatValue_.Clone();
      repeatedInt32Value_ = other.repeatedInt32Value_.Clone();
      repeatedInt64Value_ = other.repeatedInt64Value_.Clone();
      repeatedMessageValue_ = other.repeatedMessageValue_.Clone();
      repeatedSfixed32Value_ = other.repeatedSfixed32Value_.Clone();
      repeatedSfixed64Value_ = other.repeatedSfixed64Value_.Clone();
      repeatedSint32Value_ = other.repeatedSint32Value_.Clone();
      repeatedSint64Value_ = other.repeatedSint64Value_.Clone();
      repeatedStringValue_ = other.repeatedStringValue_.Clone();
      repeatedUint32Value_ = other.repeatedUint32Value_.Clone();
      repeatedUint64Value_ = other.repeatedUint64Value_.Clone();
      map1_ = other.map1_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiFields Clone() {
      return new MultiFields(this);
    }

    /// <summary>Field number for the "bool_flag" field.</summary>
    public const int BoolFlagFieldNumber = 1;
    private bool boolFlag_;
    /// <summary>
    /// basic definitions 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BoolFlag {
      get { return boolFlag_; }
      set {
        boolFlag_ = value;
      }
    }

    /// <summary>Field number for the "bytes_value" field.</summary>
    public const int BytesValueFieldNumber = 2;
    private pb::ByteString bytesValue_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BytesValue {
      get { return bytesValue_; }
      set {
        bytesValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "double_value" field.</summary>
    public const int DoubleValueFieldNumber = 3;
    private double doubleValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double DoubleValue {
      get { return doubleValue_; }
      set {
        doubleValue_ = value;
      }
    }

    /// <summary>Field number for the "enum_value" field.</summary>
    public const int EnumValueFieldNumber = 4;
    private global::sRPC.Test.Proto.EnumObject enumValue_ = global::sRPC.Test.Proto.EnumObject.DefaultValue;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::sRPC.Test.Proto.EnumObject EnumValue {
      get { return enumValue_; }
      set {
        enumValue_ = value;
      }
    }

    /// <summary>Field number for the "fixed32_value" field.</summary>
    public const int Fixed32ValueFieldNumber = 5;
    private uint fixed32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Fixed32Value {
      get { return fixed32Value_; }
      set {
        fixed32Value_ = value;
      }
    }

    /// <summary>Field number for the "fixed64_value" field.</summary>
    public const int Fixed64ValueFieldNumber = 6;
    private ulong fixed64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Fixed64Value {
      get { return fixed64Value_; }
      set {
        fixed64Value_ = value;
      }
    }

    /// <summary>Field number for the "float_value" field.</summary>
    public const int FloatValueFieldNumber = 7;
    private float floatValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float FloatValue {
      get { return floatValue_; }
      set {
        floatValue_ = value;
      }
    }

    /// <summary>Field number for the "int32_value" field.</summary>
    public const int Int32ValueFieldNumber = 8;
    private int int32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int32Value {
      get { return int32Value_; }
      set {
        int32Value_ = value;
      }
    }

    /// <summary>Field number for the "int64_value" field.</summary>
    public const int Int64ValueFieldNumber = 9;
    private long int64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Int64Value {
      get { return int64Value_; }
      set {
        int64Value_ = value;
      }
    }

    /// <summary>Field number for the "message_value" field.</summary>
    public const int MessageValueFieldNumber = 10;
    private global::Google.Protobuf.WellKnownTypes.Timestamp messageValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp MessageValue {
      get { return messageValue_; }
      set {
        messageValue_ = value;
      }
    }

    /// <summary>Field number for the "sfixed32_value" field.</summary>
    public const int Sfixed32ValueFieldNumber = 11;
    private int sfixed32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sfixed32Value {
      get { return sfixed32Value_; }
      set {
        sfixed32Value_ = value;
      }
    }

    /// <summary>Field number for the "sfixed64_value" field.</summary>
    public const int Sfixed64ValueFieldNumber = 12;
    private long sfixed64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Sfixed64Value {
      get { return sfixed64Value_; }
      set {
        sfixed64Value_ = value;
      }
    }

    /// <summary>Field number for the "sint32_value" field.</summary>
    public const int Sint32ValueFieldNumber = 13;
    private int sint32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Sint32Value {
      get { return sint32Value_; }
      set {
        sint32Value_ = value;
      }
    }

    /// <summary>Field number for the "sint64_value" field.</summary>
    public const int Sint64ValueFieldNumber = 14;
    private long sint64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Sint64Value {
      get { return sint64Value_; }
      set {
        sint64Value_ = value;
      }
    }

    /// <summary>Field number for the "string_value" field.</summary>
    public const int StringValueFieldNumber = 15;
    private string stringValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue {
      get { return stringValue_; }
      set {
        stringValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uint32_value" field.</summary>
    public const int Uint32ValueFieldNumber = 16;
    private uint uint32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Uint32Value {
      get { return uint32Value_; }
      set {
        uint32Value_ = value;
      }
    }

    /// <summary>Field number for the "uint64_value" field.</summary>
    public const int Uint64ValueFieldNumber = 17;
    private ulong uint64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Uint64Value {
      get { return uint64Value_; }
      set {
        uint64Value_ = value;
      }
    }

    /// <summary>Field number for the "repeated_bool_flag" field.</summary>
    public const int RepeatedBoolFlagFieldNumber = 21;
    private static readonly pb::FieldCodec<bool> _repeated_repeatedBoolFlag_codec
        = pb::FieldCodec.ForBool(170);
    private readonly pbc::RepeatedField<bool> repeatedBoolFlag_ = new pbc::RepeatedField<bool>();
    /// <summary>
    /// repeated definitions 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<bool> RepeatedBoolFlag {
      get { return repeatedBoolFlag_; }
    }

    /// <summary>Field number for the "repeated_bytes_value" field.</summary>
    public const int RepeatedBytesValueFieldNumber = 22;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_repeatedBytesValue_codec
        = pb::FieldCodec.ForBytes(178);
    private readonly pbc::RepeatedField<pb::ByteString> repeatedBytesValue_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<pb::ByteString> RepeatedBytesValue {
      get { return repeatedBytesValue_; }
    }

    /// <summary>Field number for the "repeated_double_value" field.</summary>
    public const int RepeatedDoubleValueFieldNumber = 23;
    private static readonly pb::FieldCodec<double> _repeated_repeatedDoubleValue_codec
        = pb::FieldCodec.ForDouble(186);
    private readonly pbc::RepeatedField<double> repeatedDoubleValue_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<double> RepeatedDoubleValue {
      get { return repeatedDoubleValue_; }
    }

    /// <summary>Field number for the "repeated_enum_value" field.</summary>
    public const int RepeatedEnumValueFieldNumber = 24;
    private static readonly pb::FieldCodec<global::sRPC.Test.Proto.EnumObject> _repeated_repeatedEnumValue_codec
        = pb::FieldCodec.ForEnum(194, x => (int) x, x => (global::sRPC.Test.Proto.EnumObject) x);
    private readonly pbc::RepeatedField<global::sRPC.Test.Proto.EnumObject> repeatedEnumValue_ = new pbc::RepeatedField<global::sRPC.Test.Proto.EnumObject>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::sRPC.Test.Proto.EnumObject> RepeatedEnumValue {
      get { return repeatedEnumValue_; }
    }

    /// <summary>Field number for the "repeated_fixed32_value" field.</summary>
    public const int RepeatedFixed32ValueFieldNumber = 25;
    private static readonly pb::FieldCodec<uint> _repeated_repeatedFixed32Value_codec
        = pb::FieldCodec.ForFixed32(202);
    private readonly pbc::RepeatedField<uint> repeatedFixed32Value_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> RepeatedFixed32Value {
      get { return repeatedFixed32Value_; }
    }

    /// <summary>Field number for the "repeated_fixed64_value" field.</summary>
    public const int RepeatedFixed64ValueFieldNumber = 26;
    private static readonly pb::FieldCodec<ulong> _repeated_repeatedFixed64Value_codec
        = pb::FieldCodec.ForFixed64(210);
    private readonly pbc::RepeatedField<ulong> repeatedFixed64Value_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> RepeatedFixed64Value {
      get { return repeatedFixed64Value_; }
    }

    /// <summary>Field number for the "repeated_float_value" field.</summary>
    public const int RepeatedFloatValueFieldNumber = 27;
    private static readonly pb::FieldCodec<float> _repeated_repeatedFloatValue_codec
        = pb::FieldCodec.ForFloat(218);
    private readonly pbc::RepeatedField<float> repeatedFloatValue_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> RepeatedFloatValue {
      get { return repeatedFloatValue_; }
    }

    /// <summary>Field number for the "repeated_int32_value" field.</summary>
    public const int RepeatedInt32ValueFieldNumber = 28;
    private static readonly pb::FieldCodec<int> _repeated_repeatedInt32Value_codec
        = pb::FieldCodec.ForInt32(226);
    private readonly pbc::RepeatedField<int> repeatedInt32Value_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> RepeatedInt32Value {
      get { return repeatedInt32Value_; }
    }

    /// <summary>Field number for the "repeated_int64_value" field.</summary>
    public const int RepeatedInt64ValueFieldNumber = 29;
    private static readonly pb::FieldCodec<long> _repeated_repeatedInt64Value_codec
        = pb::FieldCodec.ForInt64(234);
    private readonly pbc::RepeatedField<long> repeatedInt64Value_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RepeatedInt64Value {
      get { return repeatedInt64Value_; }
    }

    /// <summary>Field number for the "repeated_message_value" field.</summary>
    public const int RepeatedMessageValueFieldNumber = 30;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Timestamp> _repeated_repeatedMessageValue_codec
        = pb::FieldCodec.ForMessage(242, global::Google.Protobuf.WellKnownTypes.Timestamp.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp> repeatedMessageValue_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp> RepeatedMessageValue {
      get { return repeatedMessageValue_; }
    }

    /// <summary>Field number for the "repeated_sfixed32_value" field.</summary>
    public const int RepeatedSfixed32ValueFieldNumber = 31;
    private static readonly pb::FieldCodec<int> _repeated_repeatedSfixed32Value_codec
        = pb::FieldCodec.ForSFixed32(250);
    private readonly pbc::RepeatedField<int> repeatedSfixed32Value_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> RepeatedSfixed32Value {
      get { return repeatedSfixed32Value_; }
    }

    /// <summary>Field number for the "repeated_sfixed64_value" field.</summary>
    public const int RepeatedSfixed64ValueFieldNumber = 32;
    private static readonly pb::FieldCodec<long> _repeated_repeatedSfixed64Value_codec
        = pb::FieldCodec.ForSFixed64(258);
    private readonly pbc::RepeatedField<long> repeatedSfixed64Value_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RepeatedSfixed64Value {
      get { return repeatedSfixed64Value_; }
    }

    /// <summary>Field number for the "repeated_sint32_value" field.</summary>
    public const int RepeatedSint32ValueFieldNumber = 33;
    private static readonly pb::FieldCodec<int> _repeated_repeatedSint32Value_codec
        = pb::FieldCodec.ForSInt32(266);
    private readonly pbc::RepeatedField<int> repeatedSint32Value_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> RepeatedSint32Value {
      get { return repeatedSint32Value_; }
    }

    /// <summary>Field number for the "repeated_sint64_value" field.</summary>
    public const int RepeatedSint64ValueFieldNumber = 34;
    private static readonly pb::FieldCodec<long> _repeated_repeatedSint64Value_codec
        = pb::FieldCodec.ForSInt64(274);
    private readonly pbc::RepeatedField<long> repeatedSint64Value_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> RepeatedSint64Value {
      get { return repeatedSint64Value_; }
    }

    /// <summary>Field number for the "repeated_string_value" field.</summary>
    public const int RepeatedStringValueFieldNumber = 35;
    private static readonly pb::FieldCodec<string> _repeated_repeatedStringValue_codec
        = pb::FieldCodec.ForString(282);
    private readonly pbc::RepeatedField<string> repeatedStringValue_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> RepeatedStringValue {
      get { return repeatedStringValue_; }
    }

    /// <summary>Field number for the "repeated_uint32_value" field.</summary>
    public const int RepeatedUint32ValueFieldNumber = 36;
    private static readonly pb::FieldCodec<uint> _repeated_repeatedUint32Value_codec
        = pb::FieldCodec.ForUInt32(290);
    private readonly pbc::RepeatedField<uint> repeatedUint32Value_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> RepeatedUint32Value {
      get { return repeatedUint32Value_; }
    }

    /// <summary>Field number for the "repeated_uint64_value" field.</summary>
    public const int RepeatedUint64ValueFieldNumber = 37;
    private static readonly pb::FieldCodec<ulong> _repeated_repeatedUint64Value_codec
        = pb::FieldCodec.ForUInt64(298);
    private readonly pbc::RepeatedField<ulong> repeatedUint64Value_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<ulong> RepeatedUint64Value {
      get { return repeatedUint64Value_; }
    }

    /// <summary>Field number for the "map_1" field.</summary>
    public const int Map1FieldNumber = 40;
    private static readonly pbc::MapField<int, string>.Codec _map_map1_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 322);
    private readonly pbc::MapField<int, string> map1_ = new pbc::MapField<int, string>();
    /// <summary>
    /// some map definition 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, string> Map1 {
      get { return map1_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MultiFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MultiFields other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BoolFlag != other.BoolFlag) return false;
      if (BytesValue != other.BytesValue) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
      if (EnumValue != other.EnumValue) return false;
      if (Fixed32Value != other.Fixed32Value) return false;
      if (Fixed64Value != other.Fixed64Value) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
      if (Int32Value != other.Int32Value) return false;
      if (Int64Value != other.Int64Value) return false;
      if (!object.Equals(MessageValue, other.MessageValue)) return false;
      if (Sfixed32Value != other.Sfixed32Value) return false;
      if (Sfixed64Value != other.Sfixed64Value) return false;
      if (Sint32Value != other.Sint32Value) return false;
      if (Sint64Value != other.Sint64Value) return false;
      if (StringValue != other.StringValue) return false;
      if (Uint32Value != other.Uint32Value) return false;
      if (Uint64Value != other.Uint64Value) return false;
      if(!repeatedBoolFlag_.Equals(other.repeatedBoolFlag_)) return false;
      if(!repeatedBytesValue_.Equals(other.repeatedBytesValue_)) return false;
      if(!repeatedDoubleValue_.Equals(other.repeatedDoubleValue_)) return false;
      if(!repeatedEnumValue_.Equals(other.repeatedEnumValue_)) return false;
      if(!repeatedFixed32Value_.Equals(other.repeatedFixed32Value_)) return false;
      if(!repeatedFixed64Value_.Equals(other.repeatedFixed64Value_)) return false;
      if(!repeatedFloatValue_.Equals(other.repeatedFloatValue_)) return false;
      if(!repeatedInt32Value_.Equals(other.repeatedInt32Value_)) return false;
      if(!repeatedInt64Value_.Equals(other.repeatedInt64Value_)) return false;
      if(!repeatedMessageValue_.Equals(other.repeatedMessageValue_)) return false;
      if(!repeatedSfixed32Value_.Equals(other.repeatedSfixed32Value_)) return false;
      if(!repeatedSfixed64Value_.Equals(other.repeatedSfixed64Value_)) return false;
      if(!repeatedSint32Value_.Equals(other.repeatedSint32Value_)) return false;
      if(!repeatedSint64Value_.Equals(other.repeatedSint64Value_)) return false;
      if(!repeatedStringValue_.Equals(other.repeatedStringValue_)) return false;
      if(!repeatedUint32Value_.Equals(other.repeatedUint32Value_)) return false;
      if(!repeatedUint64Value_.Equals(other.repeatedUint64Value_)) return false;
      if (!Map1.Equals(other.Map1)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BoolFlag != false) hash ^= BoolFlag.GetHashCode();
      if (BytesValue.Length != 0) hash ^= BytesValue.GetHashCode();
      if (DoubleValue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
      if (EnumValue != global::sRPC.Test.Proto.EnumObject.DefaultValue) hash ^= EnumValue.GetHashCode();
      if (Fixed32Value != 0) hash ^= Fixed32Value.GetHashCode();
      if (Fixed64Value != 0UL) hash ^= Fixed64Value.GetHashCode();
      if (FloatValue != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatValue);
      if (Int32Value != 0) hash ^= Int32Value.GetHashCode();
      if (Int64Value != 0L) hash ^= Int64Value.GetHashCode();
      if (messageValue_ != null) hash ^= MessageValue.GetHashCode();
      if (Sfixed32Value != 0) hash ^= Sfixed32Value.GetHashCode();
      if (Sfixed64Value != 0L) hash ^= Sfixed64Value.GetHashCode();
      if (Sint32Value != 0) hash ^= Sint32Value.GetHashCode();
      if (Sint64Value != 0L) hash ^= Sint64Value.GetHashCode();
      if (StringValue.Length != 0) hash ^= StringValue.GetHashCode();
      if (Uint32Value != 0) hash ^= Uint32Value.GetHashCode();
      if (Uint64Value != 0UL) hash ^= Uint64Value.GetHashCode();
      hash ^= repeatedBoolFlag_.GetHashCode();
      hash ^= repeatedBytesValue_.GetHashCode();
      hash ^= repeatedDoubleValue_.GetHashCode();
      hash ^= repeatedEnumValue_.GetHashCode();
      hash ^= repeatedFixed32Value_.GetHashCode();
      hash ^= repeatedFixed64Value_.GetHashCode();
      hash ^= repeatedFloatValue_.GetHashCode();
      hash ^= repeatedInt32Value_.GetHashCode();
      hash ^= repeatedInt64Value_.GetHashCode();
      hash ^= repeatedMessageValue_.GetHashCode();
      hash ^= repeatedSfixed32Value_.GetHashCode();
      hash ^= repeatedSfixed64Value_.GetHashCode();
      hash ^= repeatedSint32Value_.GetHashCode();
      hash ^= repeatedSint64Value_.GetHashCode();
      hash ^= repeatedStringValue_.GetHashCode();
      hash ^= repeatedUint32Value_.GetHashCode();
      hash ^= repeatedUint64Value_.GetHashCode();
      hash ^= Map1.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BoolFlag != false) {
        output.WriteRawTag(8);
        output.WriteBool(BoolFlag);
      }
      if (BytesValue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(BytesValue);
      }
      if (DoubleValue != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(DoubleValue);
      }
      if (EnumValue != global::sRPC.Test.Proto.EnumObject.DefaultValue) {
        output.WriteRawTag(32);
        output.WriteEnum((int) EnumValue);
      }
      if (Fixed32Value != 0) {
        output.WriteRawTag(45);
        output.WriteFixed32(Fixed32Value);
      }
      if (Fixed64Value != 0UL) {
        output.WriteRawTag(49);
        output.WriteFixed64(Fixed64Value);
      }
      if (FloatValue != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(FloatValue);
      }
      if (Int32Value != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Int32Value);
      }
      if (Int64Value != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(Int64Value);
      }
      if (messageValue_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(MessageValue);
      }
      if (Sfixed32Value != 0) {
        output.WriteRawTag(93);
        output.WriteSFixed32(Sfixed32Value);
      }
      if (Sfixed64Value != 0L) {
        output.WriteRawTag(97);
        output.WriteSFixed64(Sfixed64Value);
      }
      if (Sint32Value != 0) {
        output.WriteRawTag(104);
        output.WriteSInt32(Sint32Value);
      }
      if (Sint64Value != 0L) {
        output.WriteRawTag(112);
        output.WriteSInt64(Sint64Value);
      }
      if (StringValue.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(StringValue);
      }
      if (Uint32Value != 0) {
        output.WriteRawTag(128, 1);
        output.WriteUInt32(Uint32Value);
      }
      if (Uint64Value != 0UL) {
        output.WriteRawTag(136, 1);
        output.WriteUInt64(Uint64Value);
      }
      repeatedBoolFlag_.WriteTo(output, _repeated_repeatedBoolFlag_codec);
      repeatedBytesValue_.WriteTo(output, _repeated_repeatedBytesValue_codec);
      repeatedDoubleValue_.WriteTo(output, _repeated_repeatedDoubleValue_codec);
      repeatedEnumValue_.WriteTo(output, _repeated_repeatedEnumValue_codec);
      repeatedFixed32Value_.WriteTo(output, _repeated_repeatedFixed32Value_codec);
      repeatedFixed64Value_.WriteTo(output, _repeated_repeatedFixed64Value_codec);
      repeatedFloatValue_.WriteTo(output, _repeated_repeatedFloatValue_codec);
      repeatedInt32Value_.WriteTo(output, _repeated_repeatedInt32Value_codec);
      repeatedInt64Value_.WriteTo(output, _repeated_repeatedInt64Value_codec);
      repeatedMessageValue_.WriteTo(output, _repeated_repeatedMessageValue_codec);
      repeatedSfixed32Value_.WriteTo(output, _repeated_repeatedSfixed32Value_codec);
      repeatedSfixed64Value_.WriteTo(output, _repeated_repeatedSfixed64Value_codec);
      repeatedSint32Value_.WriteTo(output, _repeated_repeatedSint32Value_codec);
      repeatedSint64Value_.WriteTo(output, _repeated_repeatedSint64Value_codec);
      repeatedStringValue_.WriteTo(output, _repeated_repeatedStringValue_codec);
      repeatedUint32Value_.WriteTo(output, _repeated_repeatedUint32Value_codec);
      repeatedUint64Value_.WriteTo(output, _repeated_repeatedUint64Value_codec);
      map1_.WriteTo(output, _map_map1_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BoolFlag != false) {
        size += 1 + 1;
      }
      if (BytesValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesValue);
      }
      if (DoubleValue != 0D) {
        size += 1 + 8;
      }
      if (EnumValue != global::sRPC.Test.Proto.EnumObject.DefaultValue) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EnumValue);
      }
      if (Fixed32Value != 0) {
        size += 1 + 4;
      }
      if (Fixed64Value != 0UL) {
        size += 1 + 8;
      }
      if (FloatValue != 0F) {
        size += 1 + 4;
      }
      if (Int32Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int32Value);
      }
      if (Int64Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Int64Value);
      }
      if (messageValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MessageValue);
      }
      if (Sfixed32Value != 0) {
        size += 1 + 4;
      }
      if (Sfixed64Value != 0L) {
        size += 1 + 8;
      }
      if (Sint32Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Sint32Value);
      }
      if (Sint64Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeSInt64Size(Sint64Value);
      }
      if (StringValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
      }
      if (Uint32Value != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Uint32Value);
      }
      if (Uint64Value != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(Uint64Value);
      }
      size += repeatedBoolFlag_.CalculateSize(_repeated_repeatedBoolFlag_codec);
      size += repeatedBytesValue_.CalculateSize(_repeated_repeatedBytesValue_codec);
      size += repeatedDoubleValue_.CalculateSize(_repeated_repeatedDoubleValue_codec);
      size += repeatedEnumValue_.CalculateSize(_repeated_repeatedEnumValue_codec);
      size += repeatedFixed32Value_.CalculateSize(_repeated_repeatedFixed32Value_codec);
      size += repeatedFixed64Value_.CalculateSize(_repeated_repeatedFixed64Value_codec);
      size += repeatedFloatValue_.CalculateSize(_repeated_repeatedFloatValue_codec);
      size += repeatedInt32Value_.CalculateSize(_repeated_repeatedInt32Value_codec);
      size += repeatedInt64Value_.CalculateSize(_repeated_repeatedInt64Value_codec);
      size += repeatedMessageValue_.CalculateSize(_repeated_repeatedMessageValue_codec);
      size += repeatedSfixed32Value_.CalculateSize(_repeated_repeatedSfixed32Value_codec);
      size += repeatedSfixed64Value_.CalculateSize(_repeated_repeatedSfixed64Value_codec);
      size += repeatedSint32Value_.CalculateSize(_repeated_repeatedSint32Value_codec);
      size += repeatedSint64Value_.CalculateSize(_repeated_repeatedSint64Value_codec);
      size += repeatedStringValue_.CalculateSize(_repeated_repeatedStringValue_codec);
      size += repeatedUint32Value_.CalculateSize(_repeated_repeatedUint32Value_codec);
      size += repeatedUint64Value_.CalculateSize(_repeated_repeatedUint64Value_codec);
      size += map1_.CalculateSize(_map_map1_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MultiFields other) {
      if (other == null) {
        return;
      }
      if (other.BoolFlag != false) {
        BoolFlag = other.BoolFlag;
      }
      if (other.BytesValue.Length != 0) {
        BytesValue = other.BytesValue;
      }
      if (other.DoubleValue != 0D) {
        DoubleValue = other.DoubleValue;
      }
      if (other.EnumValue != global::sRPC.Test.Proto.EnumObject.DefaultValue) {
        EnumValue = other.EnumValue;
      }
      if (other.Fixed32Value != 0) {
        Fixed32Value = other.Fixed32Value;
      }
      if (other.Fixed64Value != 0UL) {
        Fixed64Value = other.Fixed64Value;
      }
      if (other.FloatValue != 0F) {
        FloatValue = other.FloatValue;
      }
      if (other.Int32Value != 0) {
        Int32Value = other.Int32Value;
      }
      if (other.Int64Value != 0L) {
        Int64Value = other.Int64Value;
      }
      if (other.messageValue_ != null) {
        if (messageValue_ == null) {
          MessageValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        MessageValue.MergeFrom(other.MessageValue);
      }
      if (other.Sfixed32Value != 0) {
        Sfixed32Value = other.Sfixed32Value;
      }
      if (other.Sfixed64Value != 0L) {
        Sfixed64Value = other.Sfixed64Value;
      }
      if (other.Sint32Value != 0) {
        Sint32Value = other.Sint32Value;
      }
      if (other.Sint64Value != 0L) {
        Sint64Value = other.Sint64Value;
      }
      if (other.StringValue.Length != 0) {
        StringValue = other.StringValue;
      }
      if (other.Uint32Value != 0) {
        Uint32Value = other.Uint32Value;
      }
      if (other.Uint64Value != 0UL) {
        Uint64Value = other.Uint64Value;
      }
      repeatedBoolFlag_.Add(other.repeatedBoolFlag_);
      repeatedBytesValue_.Add(other.repeatedBytesValue_);
      repeatedDoubleValue_.Add(other.repeatedDoubleValue_);
      repeatedEnumValue_.Add(other.repeatedEnumValue_);
      repeatedFixed32Value_.Add(other.repeatedFixed32Value_);
      repeatedFixed64Value_.Add(other.repeatedFixed64Value_);
      repeatedFloatValue_.Add(other.repeatedFloatValue_);
      repeatedInt32Value_.Add(other.repeatedInt32Value_);
      repeatedInt64Value_.Add(other.repeatedInt64Value_);
      repeatedMessageValue_.Add(other.repeatedMessageValue_);
      repeatedSfixed32Value_.Add(other.repeatedSfixed32Value_);
      repeatedSfixed64Value_.Add(other.repeatedSfixed64Value_);
      repeatedSint32Value_.Add(other.repeatedSint32Value_);
      repeatedSint64Value_.Add(other.repeatedSint64Value_);
      repeatedStringValue_.Add(other.repeatedStringValue_);
      repeatedUint32Value_.Add(other.repeatedUint32Value_);
      repeatedUint64Value_.Add(other.repeatedUint64Value_);
      map1_.Add(other.map1_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BoolFlag = input.ReadBool();
            break;
          }
          case 18: {
            BytesValue = input.ReadBytes();
            break;
          }
          case 25: {
            DoubleValue = input.ReadDouble();
            break;
          }
          case 32: {
            EnumValue = (global::sRPC.Test.Proto.EnumObject) input.ReadEnum();
            break;
          }
          case 45: {
            Fixed32Value = input.ReadFixed32();
            break;
          }
          case 49: {
            Fixed64Value = input.ReadFixed64();
            break;
          }
          case 61: {
            FloatValue = input.ReadFloat();
            break;
          }
          case 64: {
            Int32Value = input.ReadInt32();
            break;
          }
          case 72: {
            Int64Value = input.ReadInt64();
            break;
          }
          case 82: {
            if (messageValue_ == null) {
              MessageValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(MessageValue);
            break;
          }
          case 93: {
            Sfixed32Value = input.ReadSFixed32();
            break;
          }
          case 97: {
            Sfixed64Value = input.ReadSFixed64();
            break;
          }
          case 104: {
            Sint32Value = input.ReadSInt32();
            break;
          }
          case 112: {
            Sint64Value = input.ReadSInt64();
            break;
          }
          case 122: {
            StringValue = input.ReadString();
            break;
          }
          case 128: {
            Uint32Value = input.ReadUInt32();
            break;
          }
          case 136: {
            Uint64Value = input.ReadUInt64();
            break;
          }
          case 170:
          case 168: {
            repeatedBoolFlag_.AddEntriesFrom(input, _repeated_repeatedBoolFlag_codec);
            break;
          }
          case 178: {
            repeatedBytesValue_.AddEntriesFrom(input, _repeated_repeatedBytesValue_codec);
            break;
          }
          case 186:
          case 185: {
            repeatedDoubleValue_.AddEntriesFrom(input, _repeated_repeatedDoubleValue_codec);
            break;
          }
          case 194:
          case 192: {
            repeatedEnumValue_.AddEntriesFrom(input, _repeated_repeatedEnumValue_codec);
            break;
          }
          case 202:
          case 205: {
            repeatedFixed32Value_.AddEntriesFrom(input, _repeated_repeatedFixed32Value_codec);
            break;
          }
          case 210:
          case 209: {
            repeatedFixed64Value_.AddEntriesFrom(input, _repeated_repeatedFixed64Value_codec);
            break;
          }
          case 218:
          case 221: {
            repeatedFloatValue_.AddEntriesFrom(input, _repeated_repeatedFloatValue_codec);
            break;
          }
          case 226:
          case 224: {
            repeatedInt32Value_.AddEntriesFrom(input, _repeated_repeatedInt32Value_codec);
            break;
          }
          case 234:
          case 232: {
            repeatedInt64Value_.AddEntriesFrom(input, _repeated_repeatedInt64Value_codec);
            break;
          }
          case 242: {
            repeatedMessageValue_.AddEntriesFrom(input, _repeated_repeatedMessageValue_codec);
            break;
          }
          case 250:
          case 253: {
            repeatedSfixed32Value_.AddEntriesFrom(input, _repeated_repeatedSfixed32Value_codec);
            break;
          }
          case 258:
          case 257: {
            repeatedSfixed64Value_.AddEntriesFrom(input, _repeated_repeatedSfixed64Value_codec);
            break;
          }
          case 266:
          case 264: {
            repeatedSint32Value_.AddEntriesFrom(input, _repeated_repeatedSint32Value_codec);
            break;
          }
          case 274:
          case 272: {
            repeatedSint64Value_.AddEntriesFrom(input, _repeated_repeatedSint64Value_codec);
            break;
          }
          case 282: {
            repeatedStringValue_.AddEntriesFrom(input, _repeated_repeatedStringValue_codec);
            break;
          }
          case 290:
          case 288: {
            repeatedUint32Value_.AddEntriesFrom(input, _repeated_repeatedUint32Value_codec);
            break;
          }
          case 298:
          case 296: {
            repeatedUint64Value_.AddEntriesFrom(input, _repeated_repeatedUint64Value_codec);
            break;
          }
          case 322: {
            map1_.AddEntriesFrom(input, _map_map1_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Identical : pb::IMessage<Identical> {
    private static readonly pb::MessageParser<Identical> _parser = new pb::MessageParser<Identical>(() => new Identical());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Identical> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::sRPC.Test.Proto.BuildTestServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identical() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identical(Identical other) : this() {
      identical_ = other.identical_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Identical Clone() {
      return new Identical(this);
    }

    /// <summary>Field number for the "identical" field.</summary>
    public const int Identical_FieldNumber = 1;
    private pb::ByteString identical_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Identical_ {
      get { return identical_; }
      set {
        identical_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Identical);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Identical other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Identical_ != other.Identical_) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Identical_.Length != 0) hash ^= Identical_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Identical_.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Identical_);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Identical_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Identical_);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Identical other) {
      if (other == null) {
        return;
      }
      if (other.Identical_.Length != 0) {
        Identical_ = other.Identical_;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Identical_ = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
